##---
# Source: strimzi-kafka-operator/templates/03-ClusterRole-strimzi-kafka-broker.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: strimzi-kafka-broker
  labels:
    app: strimzi-kafka-operator
    chart: strimzi-kafka-operator-0.1.0
    component: broker-role
    release: RELEASE-NAME
    heritage: Tiller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
